server:
  servlet:
    context-path: /api
    port: 8080

# DB와 secret key 세팅 값
spring:
  profiles:
    active: prod
    include: secret
---
spring:
  profiles:
    active: dev
    include: secret
---
spring:
  profiles:
    active: local
    include: secret


  jpa:
    hibernate:
      format_sql: true
      show_sql: false

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB


cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${ACCESS_KEY}
      secretKey: ${SECRET_KEY}
